### ISSUE TITLE
[Fix] 회원가입 플로우 qa

### ISSUE THREAD

**Issue by joonBaek12** [TeamPophory/pophory-iOS#106]
## Issue

회원가입 플로우 qa

## To-do

- [x] 키보드 외 영역 터치 시 키보드 내림
- [x] 앨범 커버 선택시 체크표시
- [ ] 싱단 인디케이터 바 
- [x] 텍스트필드 x버튼
- [x] 앨범 이미지 스와이프
- [x] 정규식
- [x] 폰트
- [ ] 버튼 비활성화 색상 변경
- [ ] shared 파일 만들기
