### ISSUE TITLE
[Chore] 내 사진 2차 스프린트 UI 업데이트 구현

### ISSUE THREAD

**Issue by joonBaek12** [TeamPophory/pophory-iOS#158]
## Issue

내 사진 2차 스프린트 업데이트 구현

## To-do

- [ ] 공유 아이콘 추가
- [x] 사진관 표기 디자인 수정
- [ ] 삭제하기 버튼 컬러 변경
- [ ] 공유버튼 -> 모달창
- [x] 사진관 미선택 시 사진관태그 x
