### ISSUE TITLE
[Fix] 2차 QA 반영

### ISSUE THREAD

**Issue by Joon9750** [TeamPophory/pophory-iOS#175]
## Issue

- 2차 QA 반영

## To-do

- [x] 내 서랍 : 팝업 아쉬지만→ 아쉽지만 (텍스트 확인해주세용)
- [x] 내 서랍 : 15장 추가하자마자 꽉 찬 팝업 뜹니다. 한 번 더 추가 시 뜨도록 바꿔주세요!
- [x] 내 서랍 : 15장이 넘어가면 사진 추가 화면으로 넘어가지 않고, 팝업만 떠야 합니다!
- [x] 내 앨범 : 내 앨범에서 사진 15장 있을 때 추가하기 버튼 막아야함
- [x] 내 앨범 : 빈 화면 (포포리 사진) 테두리 있는 에셋으로 바뀌어야함
- [x] 내 앨범 : 정렬 선택하기 팝업에서 라벨 - 옛날에 찍은 순, 보이는 라벨 - 과거에 찍은 순
- [x] 내 앨범 : 앨범 정렬 버그 수정
