### ISSUE TITLE
[Fix] 2차 스프린트 QA 반영

### ISSUE THREAD

**Issue by yeahh315** [TeamPophory/pophory-iOS#194]
## Issue
2차 스프린트 QA 반영

## To-do
- [x] 내 앨범 없애기
- [x] 내장 갤러리 재실행시 선택된 사진 해제되게
- [x] 날짜 형식 수정 (요일 빼기)
- [x] 사진 layout 다시 잡기
- [x] 사진관 재선택 시 셀 선택되어있게
- [x] 날짜 재선택 시 선택했던 날짜가 캘린더에 선택되어있게
