### ISSUE TITLE
[Feat] 이름, 닉네임 입력 뷰 구현

### ISSUE THREAD

**Issue by joonBaek12** [TeamPophory/pophory-iOS#20]
## Issue

이름, 닉네임 입력 뷰를 구현합니다.
## To-do

- [x] keyboard following button
- [x] 지정된 텍스트만 색깔 바꿔주는 메서드
- [ ] 텍스트필드 정규식 조건에 따른 분기처리
- [x] 텍스트뷰 카운트에 따라 coundLabel 변경
