### ISSUE TITLE
[Fix] 온보딩-회원가입 플로우 2차 스프린트 qa 반영

### ISSUE THREAD

**Issue by joonBaek12** [TeamPophory/pophory-iOS#201]
## Issue

2차 스프린트 qa 미반영 건에 대한 수정사항입니다.

## To-do

- [ ] 애플로그인 버튼 레이아웃 수정
- [ ] 앨범 커버선택 초기값 지정
- [ ] 텍스트필드에서 개행시 버튼 비활성화 이슈
