### ISSUE TITLE
[Chore] v.1..1.1 업데이트 반영 사항

### ISSUE THREAD

**Issue by joonBaek12** [TeamPophory/pophory-iOS#211]
## Issue

v.1.1.1 업데이트 반영 브랜치 입니다.

## To-do

- [x] 버전 관리
- [x] 자동로그인 코드 누락 커밋
- [ ] 앱 이름 변경
- [x] 홍보문구 변경
- [x] 자세한 설명 변경
- [ ] 앱 미리보기/스크린샷 변경
